# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
  repositories:
    provision: 'git@github.com:puppetlabs/provision.git'
    puppet_agent: 'git@github.com:puppetlabs/puppetlabs-puppet_agent'
    facts: 'git@github.com:puppetlabs/puppetlabs-facts'
  # Should go away when Attempting to work around PDK-1137(https://tickets.puppetlabs.com/browse/PDK-1137)
  # is resolved.
  symlinks:
    azure_key_vault: '#{source_dir}'
